### ISSUE TITLE
facebook /comments error: "notes API is deprecated"

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#480]
facebook warns me, that bridgy lost access to facebook, and after every single time i renew and grant access, i lose it after reloading my bridgy facebook page:
https://www.brid.gy/facebook/548616784#

![bildschirmfoto 2015-09-21 um 18 14 08](https://cloud.githubusercontent.com/assets/4541494/9997495/b387fb18-608c-11e5-81c4-cb3c99303e77.png)

**Comment by snarfed** [comment]
oh man, that's annoying. sorry about that! i'll look soon.

**Comment by snarfed** [comment]
here's the error response from FB. it triggers this since it's type `OAuthException`. we're seeing more and more FB errors with that type that aren't actually auth problems; we should probably narrow our logic for handling it.

```
Error 400, response body: {"error":{"message":"(#12) notes API is deprecated for versions v2.0 and higher","type":"OAuthException","code":12}}
```

**Comment by snarfed** [comment]
the annoying part is that this is happening on `/comments`, ie we're not explicitly using the notes API anywhere. i'm guessing one of the ids getting passed in the `ids` param is a note. i can probably filter those out based on `type` or something similar.

**Comment by diplix** [comment]
yes, i just created a note.

**Comment by snarfed** [comment]
looks like these are easy to filter using `"type": "note"`. the FB object looks like:

```json
{
  "id": "548616784_10153288460596785",
  "story": "Felix Schwenzel shared his note.",
  "type": "note",
  ...
}
```

**Comment by diplix** [comment]
as of now, it didn’t fix the permission problem, so i deleted the note. (almost) nobody took notice of it anyways. deleting the note fixed it on bridgy for now.

i’ll be happy to publish another note for testing purposes again.

**Comment by snarfed** [comment]
hey, sorry, i'm actually still working on the fix for this. the commits attached here are part of it, but they're not complete yet.

thanks for the offer! i'll let you know when it's ready.

**Comment by snarfed** [comment]
done!

**Comment by diplix** [comment]
i did it again. i published a note (they are „new“). bridgy now shows a less aggressive error message, or rather, doesn’t forget my facebook permissions, but there still seems to be an error occuring while polling:
<img width="654" alt="bildschirmfoto 2015-09-26 um 00 10 12" src="https://cloud.githubusercontent.com/assets/4541494/10113310/37c11d2a-63e3-11e5-81f1-012e1c053a7a.png">

but may be that little exclamation mark is harmless?

**Comment by snarfed** [comment]
damn, you're right, looks like this isn't fully fixed. reopening. thanks for the test case!

**Comment by diplix** [comment]
thanks, the error went away. 
the depreciated notes API seems to not be needed anymore, likes and comments (no comment replys though) are beeing pulled from facebook. i’m not sure which of the two syndication links i set is actually working:
https://www.facebook.com/10153295535801785
https://www.facebook.com/548616784/posts/10153295535801785

the second link links to a facebook status announcing the note, i guess thats the one that does the magic. this is the original:
http://wirres.net/article/articleview/8611/1/6/

i’m wondering if i shpuld open a separate issue because facebook comment-replys are not pulled anymore. i have the feeling that this was something that worked a while ago and went away again. can anyone confim that?

**Comment by snarfed** [comment]
ugh, thanks for that report. i think that might be #492. I'll confirm soon. feel free to follow along there!
