### ISSUE TITLE
fetching facebook nested comments

### ISSUE THREAD

**Issue by fiatjaf** [snarfed/bridgy#502]
Like the ones in this post: https://www.facebook.com/pollyannasouza26/posts/1005807139483710?comment_id=1005851629479261&reply_comment_id=1005882259476198&total_comments=9&comment_tracking=%7B%22tn%22%3A%22R4%22%7D

Is it possible?

**Comment by snarfed** [comment]
yes! we implemented this recently in #435. is it not working for you?

**Comment by fiatjaf** [comment]
Nice, I thought it couldn't be done!

But it is not working. I only get the top-level comments (it's my girlfriend, actually). Probably a permission-related thing? If so, how can I reauthorize the account with the new permissions?

**Comment by snarfed** [comment]
user page is https://www.brid.gy/facebook/987100564687701

**Comment by snarfed** [comment]
@fiatjaf i'm investigating. fingers crossed!

**Comment by snarfed** [comment]
@fiatjaf it looks like bridgy is sending the threaded comments ok. both of the comments visible on her user page, _o problema de se sentir "uma..._ and _Fiquei encucado com essa coisa do ..._, are threaded comments.

i don't see the comments pollyanna wrote herself, though. i'll keep looking.

**Comment by snarfed** [comment]
looks like other threaded comments by pollyanna have made it to her blog ok, e.g. http://reconhecendo.me/para-colorir/corpo/#55e1eeef444bb481ad2b26a7, from https://www.facebook.com/pollyannasouza26/posts/989137021150722?comment_id=989165034481254&reply_comment_id=989173257813765.

same with other FB threaded comments by the original post's author, e.g. http://boffosocko.com/2015/07/27/algebraic-number-theory-ucla-extension/#comment-29149 .

so, i'm still not sure why the example here wasn't backfed, but there may not be a wider bug here. tentatively closing. @fiatjaf, feel free to reopen if pollyanna sees this problem again in the future!

**Comment by nekr0z** [comment]
I do see this problem with my facebook polling, I have never had a nested comment come through in Brid.gy, and I still don't see it now. Reopen?

**Comment by snarfed** [comment]
hmm. i see at least one nested comment, the one from krol zaytsev here:

http://www.evgenykuznetsov.org/2015/--35#comments
https://www.facebook.com/10152710552987085/posts/10153028291842085?comment_id=10153028884232085

I'll see if i can find a missing one.

**Comment by snarfed** [comment]
ah, this one is missing. I'll take a look.

https://m.facebook.com/comment/replies/?ctoken=10153078432857085_10153078646172085&count=1&pc=1&ft_ent_identifier=10153078432857085&gfid=AQA7sm4I-8pgpjb4

http://www.evgenykuznetsov.org/2015/untitled-5#comments

**Comment by snarfed** [comment]
interesting. it looks like we actually did send it successfully. [it's the bottom response here.](https://brid.gy/facebook/10152710552987085?responses_after=2015-10-10T18:45:20#responses) [propagate log here.](https://brid.gy/log?start_time=1444502721&key=aglzfmJyaWQtZ3lyRwsSCFJlc3BvbnNlIjl0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxNTMwMjgyOTE4NDIwODVfMTAxNTMwMjg4ODQyMzIwODUM) and the [comment handler](https://brid-gy.appspot.com/comment/facebook/10152710552987085/10153028291842085/10153028291842085_10153028884232085) is serving it ok.

i clicked the retry button in bridgy, and it resent successfully. [known shows it now.](http://www.evgenykuznetsov.org/2015/--35#comments) not sure what happened originally, but  i'd guess an FB API call in the comment handlers failed transiently, and known didn't retry.

i'm going to dig back into the one fiatjaf reported now.

**Comment by snarfed** [comment]
missing example from fiatjaf is https://www.facebook.com/pollyannasouza26/posts/1005807139483710?comment_id=1005851629479261&reply_comment_id=1005882259476198 , 2015-09-30 7:16pm PST, 2015-10-01 2:16am UTC.

**Comment by fiatjaf** [comment]
I notice previously that, at least from the logs I am able to see from the Bridgy interface, the missing comments weren't actually sent by Bridgy.

**Comment by snarfed** [comment]
smoking gun seems to be that we weren't including the post id 1005807139483710 in the
 `/comments?filter=stream&ids=...` call, which gets the nested comments.

...and yup, found the root cause. the post was ` "type": "link"`, which we lump in with `"note"`, which we don't fetch nested comments for because notes don't support them (and 400 the API call). fix is to change that type conversion.

**Comment by snarfed** [comment]
@fiatjaf agreed, bridgy never sent the missing comments in your case. i think i've fixed the bug now. it may not go back and find the old missing comments, but it should send all nested comments in the future. thanks for your patience!

**Comment by nekr0z** [comment]
Issue still persists somewhat, at least for me. See https://facebook.com/10152689443092085/posts/10153367525752085 — more than 40 comments if we count nested ones. http://www.evgenykuznetsov.org/2016/110011%25d0%25b5%25d1%2581%25d1%2582%25d1%258c-%25d1%2585%25d0%25b8%25d1%2582%25d1%2580%25d1%258b%25d0%25b9-%25d0%25b2%25d0%25be%25d0%25bf%25d1%2580%25d0%25be%25d1%2581-%25d0%25ba%25d0%25be%25d1%2582%25d0 — at least 10 comments less. Some nested comments did appear, some didn't. All the root comments did.

**Comment by snarfed** [comment]
ugh. sorry for the trouble, and thanks for filing! my guess is this is either #394, not following paging to get comments beyond the first batch that the API returns, or some other facebook API data model thing.

i've burned out some on handling FB API data model stuff recently, so it may be a bit before i dive into this. thanks again for letting me know though!

**Comment by nekr0z** [comment]
@snarfed Looks like a paging issue to me indeed: the nested comments stopped appearing at some point, while all root comments to the same post still keep appearing (perhaps because there's not too many of them).

**Comment by snarfed** [comment]
thanks again for reporting, @nekr0z! i've filed #657 for this.
